Repository NotAussie/Tilasto, pull requests merged in 2023-11, with the labels that each got.

#1 Add .gitignore and Watchers
  .gitignore
  src/watcher.py
Labels: enhancement, improvement

#2 Fixed spelling :D
  README.md
Labels: documentation, improvement

#3 Allow run.run() to run Watchers, and introduce watcher threading
  src/run.py
  src/watcher.py
Labels: enhancement, maintenance, improvement
